version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./.deploy/Dockerfile.local
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true
    tty: true
