import AppLayout from "@/app/_components/layout/app.layout";
import { getLocale, getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import type { Metadata } from "next";
import React from 'react';
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
      <NextIntlClientProvider messages={messages}>
          <AppLayout>
              {children}
          </AppLayout>
      </NextIntlClientProvider>
      </body>
    </html>
  );
}
